In [2]:
import pandas as pd

In [3]:
# pd.Series(data)
# pd.Series(data, index=None, dtype=None, name=None, copy=False, fastpath=False)

data = [1,2,3,4,5,6]

s1 = pd.Series(data) #from list

In [4]:
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [5]:
s2 = pd.Series(data, index=['a', 'b', 'c', 'd', 'e', 'f'], name='Numbers')

In [6]:
print(s2)

a    1
b    2
c    3
d    4
e    5
f    6
Name: Numbers, dtype: int64

In [7]:
data = {'a': 10, 'b': 20, 'c': 30}
s3 = pd.Series(data) #from dict
print(s3)

a    10
b    20
c    30
dtype: int64

In [8]:
# Create Series from NumPy array
import numpy as np
arr = np.array([5, 10, 15])
s4 = pd.Series(arr, index=['x', 'y', 'z'])
print(s4)

x     5
y    10
z    15
dtype: int64

In [9]:
#  Series Attributes & Properties

s2 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'], name='Scores')

print(s2)
print(s2.index)     # Index object
print(s2.values)    # NumPy array of values
print(s2.dtype)     # Data type
print(s2.name)      # Name of the Series
print(s2.shape) 
type(s2.shape)

a    10
b    20
c    30
d    40
Name: Scores, dtype: int64
Index(['a', 'b', 'c', 'd'], dtype='str')
[10 20 30 40]
int64
Scores
(4,)

tuple

#### Series Indexing & Access

In [10]:
# 1. Positional Indexing
# [10 20 30 40]
print(s2.values[0])
print(s2.values[3])

10
40

In [11]:
# iloc gets rows (and/or columns) at integer locations.

print(s2.iloc[0])

10

In [12]:
print(s2.iloc[1:3])

b    20
c    30
Name: Scores, dtype: int64

In [13]:
# 2. Label-based Indexing

# loc gets rows (and/or columns) with particular labels.
# Pandas resolves s2[0] in the following order:

# Check if 0 is a label in the index
# → If yes, return by label

# If not, and if the index is not integer-based, then treat 0 as a position
# → Return item at index position 0 (first element)

# FutureWarning: Series.__getitem__ treating keys as positions is deprecated.

# In a future version, integer keys will always be treated as 
# labels (consistent with DataFrame behavior). 
# To access a value by position, use `ser.iloc[pos]`

print(s2.values[0])

10

In [14]:
print(s2.iloc[0])

10

In [15]:
print(s2.iloc[1:3])

b    20
c    30
Name: Scores, dtype: int64

In [16]:
print(s2.loc['b'])

20

In [17]:
print(s2.loc[['b', 'd']])

b    20
d    40
Name: Scores, dtype: int64

In [18]:
s3 = pd.Series([10,20,30,40,50,60])
print(s3.loc[1])
print(s3.loc[[1,2]]) # loc will work for any label , be it numberic or alpha index. But iloc have to be used only for numeric index

20
1    20
2    30
dtype: int64

In [19]:
s4 = pd.Series([1.0,2.0,3,4,5.0])

In [20]:
s4.iloc[3]

np.float64(4.0)

In [21]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

In [22]:
df = pd.read_csv(titanic_dataset_github_url)

In [23]:
type(df)

pandas.DataFrame

In [24]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [25]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [26]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [27]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [28]:
df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [29]:
df[["Name", "Age"]].head(10)

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0
5                                   Moran, Mr. James   NaN
6                            McCarthy, Mr. Timothy J  54.0
7                     Palsson, Master. Gosta Leonard   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0

In [30]:
df.set_index("PassengerId") # or 'PassengerId'

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [31]:
df_by_passenger_id = df.set_index('PassengerId')

In [33]:
df_by_passenger_id.head(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [34]:
df_by_passenger_id.iloc[0]

Survived                          0
Pclass                            3
Name        Braund, Mr. Owen Harris
Sex                            male
Age                            22.0
SibSp                             1
Parch                             0
Ticket                    A/5 21171
Fare                           7.25
Cabin                           NaN
Embarked                          S
Name: 1, dtype: object

In [32]:
df[["Name", "Age"]].head(3).to_numpy()

array([['Braund, Mr. Owen Harris', 22.0],
       ['Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 38.0],
       ['Heikkinen, Miss. Laina', 26.0]], dtype=object)